Fix issue when pulling from cells with some types of formulas is them
BHoM/Excel_Toolkit pull request #23
Opened 2023-04-19 06:59 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #22

As stated in the issue, there are some issues with reading values from some cells that contain some types of formulas.

The code in this PR fixes the issue by falling back to the cached value of the cell for when getting the Value out fails.
I went with raising a warning if this happens, and if closedXML believes the cell needs recalculation. For all cases I have tested so far, the cached value will be correct, but raised the warning to be safe.

Saying that, I was not aware that the adapter actually recomputed the sheet to get the values. Would have assumed that it just got whatever was in the cell, so might be safe to remove the warning.
Happy for any input on this from reviewers.

### Test files

### Changelog

### Additional comments

2023-04-19 07:02 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2023-04-24 08:41 UTC, FraserGreenroyd requested changes

2023-04-24 08:41 UTC, FraserGreenroyd commented on Excel_Adapter/Convert/FromExcel/CellContents.cs
> +        public static object CellValueOrCashedValue(this IXLCell xLCell)
```suggestion
        public static object CellValueOrCachedValue(this IXLCell xLCell) 
```

2023-04-24 08:41 UTC, FraserGreenroyd commented on Excel_Adapter/Convert/FromExcel/CellContents.cs
> +                    BH.Engine.Base.Compute.RecordWarning($"Cell {xLCell?.Address?.ToString() ?? "unknown"} is flagged as needing to be recalculated, but this is not able to be done. The cached value
```suggestion
                    BH.Engine.Base.Compute.RecordWarning($"Cell {xLCell?.Address?.ToString() ?? "unknown"} is flagged as needing to be recalculated, but this is not able to be done. The cached value for this cell is returned, which for most cases is correct, but please check the validity of the value.");
```

2023-04-24 08:41 UTC, FraserGreenroyd commented on Excel_Adapter/Convert/FromExcel/CellContents.cs
> +                Value = xLCell.CellValueOrCashedValue(),
```suggestion
                Value = xLCell.CellValueOrCachedValue(),
```

2023-04-24 08:41 UTC, FraserGreenroyd commented on Excel_Adapter/CRUD/Read/Read.cs
> +                        dataRow.Add(ixlWorksheet.Cell(row.RowNumber(), column.ColumnNumber()).CellValueOrCashedValue());
```suggestion
                        dataRow.Add(ixlWorksheet.Cell(row.RowNumber(), column.ColumnNumber()).CellValueOrCachedValue());
```

2023-05-12 11:13 UTC, FraserGreenroyd approved these changes
Testing against today's alpha using the test script provided shows these two errors on the canvas:
![image](https://github.com/BHoM/Excel_Toolkit/assets/18049174/8189fe0b-3e6b-4668-a802-3088c398ab10)

![image](https://github.com/BHoM/Excel_Toolkit/assets/18049174/d48cca2e-45c8-4270-b22d-1c2640131c70)

After rebasing this PR and compiling this toolkit, the errors change to warnings:

![image](https://github.com/BHoM/Excel_Toolkit/assets/18049174/26683c8e-773f-400c-8284-b43a7a35240f)

Same for both pulls.

This did pull through values whereas the alpha did not, so this PR represents an improvement to the overall workflow. I'm happy for this to be merged and deployed for further testing via alphas.

2023-05-12 11:13 UTC, FraserGreenroyd commented
@BHoMBot check compliance
@BHoMBot check required

2023-05-12 11:51 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-05-12 11:52 UTC, merged