Change target framework and remove no longer required dependencies
BHoM/Excel_Toolkit pull request #81
Opened 2024-06-27 06:59 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #79

Changes the target framework of the debug and release build to simply be netstandard2.0 . 

Whilst attempting to do this, realised that the reason this toolkit was still on 4.7.2 net framework was the `VerifySecurityEvidenceForIsolatedStorage` to handle saving of large files. From testing with file provided in https://github.com/BHoM/Excel_UI/pull/331 this does not seem to be an issue any longer for netstandard2.0 , hence the method has been removed.

@pawelbaran would greatly appreciate if you are able to check that you are happy with this removal, given you raised this and fixed it in the first place.

Ofc general functionality of the toolkit should also be checked to ensure this does not have any other detrimental impacts on the toolkit.

### Test files

### Changelog

### Additional comments

2024-06-27 06:59 UTC, IsakNaslundBh commented
@BHoMBot check compliance

2024-06-27 07:17 UTC, IsakNaslundBh commented
@BHoMBot check project-compliance

2024-06-28 14:58 UTC, pawelbaran requested changes
Code changes make sense to me, but unfortunately Excel adapter does not work inside Revit on this PR, following exception is thrown:
![image](https://github.com/BHoM/Excel_Toolkit/assets/26874773/5ef3a3a9-4ac1-4a8c-bf35-3db04bf77bd2)

Via trial and error I identified that it is `DocumentFormat.OpenXml.Packaging.OpenXmlPackage` type (a property of `DocumentFormat.OpenXml.Packaging.SpreadsheetDocument`) that cannot be loaded.

I was trying to track down the origins using Fusion Log, got this:
![image](https://github.com/BHoM/Excel_Toolkit/assets/26874773/0e338fe8-e0a1-4d71-b134-6e8fbbcc44f9)

The above does not make much sense to me, why is `DocumentFormat.OpenXml` trying to load `System.IO.Packaging` 4.0.5, if it clearly depends on 6.0.0?
![image](https://github.com/BHoM/Excel_Toolkit/assets/26874773/33e6adbb-f50d-4bcc-a36b-ff746c4975e3)

Meanwhile, I do not have any issues with loading types from `System.IO.Packaging` directly in Push method, e.g. adding `System.IO.Packaging.Package p = null` binds nicely to 6.0.0.

Going further, at the moment of calling `Push`, `DocumentFormat.OpenXml` 2.16 is already loaded into app domain from _C:\\ProgramData\\BHoM\\Assemblies\\DocumentFormat.OpenXml.dll_, which is alright.

So to summarise: everything seems to be perfectly fine, right assemblies being loaded and referenced, until `DocumentFormat.OpenXml.Packaging.OpenXmlPackage` is reflected, causing an attempt to load `System.IO.Packaging` 4.0.5 instead of 6.0.0. My gut feeling is that there is some voodoo happening due to the app domain being owned by Revit that sits on .NET Framework, but can't find out where & why. @adecler, any ideas what could be wrong here? Suggestions how to debug deeper?

2024-07-02 09:21 UTC, adecler commented
@pawelbaran , my initial finding leads to SAP Toolkit being the potential problem as it still depends ClosedXML version 0.95:

![image](https://github.com/BHoM/Excel_Toolkit/assets/16853390/3d7c3e07-d94d-4678-b9e5-7f77c94cefd3)

2024-07-02 14:31 UTC, pawelbaran commented
Thanks for help @adecler - unfortunately it does not fix Revit :< Just tried, still getting the same exception

2024-12-16 09:54 UTC, pawelbaran commented
After the recent issue with `System.IO.Packaging` assembly raised to @michal-pekacki by the users, I had another think about fixing it - having succeeded with the initial testing, I rebased the branch and pushed the fix. Something to pick up early 8.1 I believe.

2025-01-07 10:33 UTC, pawelbaran commented
I have just rebased the branch, @IsakNaslundBh could you please have a look at the code and confirm you have nothing against the changes as the originator of the PR? @michal-pekacki could you please test and see if it solves your issues? I will do the testing of Grasshopper interop.

2025-01-07 11:02 UTC, pawelbaran commented
@BHoMBot check installer

2025-01-07 13:16 UTC, pawelbaran commented
@BHoMBot check installer

2025-01-07 15:09 UTC, michal-pekacki submitted a review, later dismissed
I tested on different Revit versions and it works without issues, happy to approve 👍

2025-01-07 17:08 UTC, pawelbaran commented
@BHoMBot check required

2025-01-08 09:34 UTC, IsakNaslundBh commented
@BHoMBot check project-compliance

2025-01-08 15:21 UTC, pawelbaran commented
@BHoMBot check installer

2025-01-09 13:09 UTC, michal-pekacki approved these changes
Tested together with https://github.com/BHoM/BHoM_Engine/pull/3453 and it works, reapproving after changes 👍

2025-01-13 10:08 UTC, pawelbaran approved these changes
Approving following testing and a chat with @adecler and @IsakNaslundBh

2025-01-13 13:40 UTC, merged